version: "3"

tasks:
  init:
    cmds:
      - git submodule init
      - git submodule update --init --recursive

  # on Visual Studio based generators CMAKE_EXPORT_COMPILE_COMMANDS will be omitted
  configure:
    cmds:
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=True -B ./build -G "{{.CLI_ARGS}}"

  build_debug:
    cmds:
      - cmake --build ./build --config Debug

  build_release:
    cmds:
      - cmake --build ./build --config Release

  clean:
    cmds:
      - cmake --build ./build --target clean
