version: "3"

tasks:
  init:
    cmds:
      - git submodule init
      - git submodule update --init --recursive

  configure:
    cmds:
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B ./build # -G {{.CLI_ARGS}}

  build_debug:
    cmds:
      - cmake --build ./build --config Debug

  build_release:
    cmds:
      - cmake --build ./build --config Release

  clean:
    cmds:
      - cmake --build ./build --target clean
