version: "3"

tasks:
  # on Visual Studio based generators CMAKE_EXPORT_COMPILE_COMMANDS and CMAKE_BUILD_TYPE will be omitted
  configure:
    cmds:
      - cmake -B ./build -G "{{.CLI_ARGS}}"

  vsconfigure:
    cmds:
      - task: configure
        vars: {CLI_ARGS: "Visual Studio 16 2019"}

  build_debug:
    cmds:
      - cmake --build ./build --config Debug

  build_release:
    cmds:
      - cmake --build ./build --config Release

  test:
    cmds:
      - cmake --build ./build --target run-tests

  clean:
    cmds:
      - cmake --build ./build --target clean
